license_id: "cc-by"
methodology: "Registry"
dataset_source: "ReliefWeb"
package_creator: "HDX Data Systems Team"
private: False
maintainer: "ab54dbbf-b25c-4c31-8bda-778ad2f39328" # Adrian Ciancio
owner_org: "de410fc7-6116-4283-9c26-67287aaa2634" # ReliefWeb
subnational: False
data_update_frequency: 7 #  Weekly
notes: |
  ReliefWeb is a humanitarian information service provided by the United Nations Office for the Coordination of Humanitarian Affairs (OCHA). ReliefWeb's editorial team monitors and collects information from more than 4,000 key sources, including humanitarian agencies at the international and local levels, governments, think-tanks and research institutions, and the media.

  ReliefWeb disaster dataset provides an overview of the situation and situation reports, news and press releases, assessments, evaluations, infographics and maps of natural disasters with humanitarian impact from 1981 until today.
