# Collector specific configuration
base_url: "https://api.reliefweb.int/v1/disasters"
tags:
  - climate hazards
  - climate-weather
  - drought
  - earthquake-tsunami
  - flooding
  - hxl
  - natural disasters
